name: Contexts
on: push
jobs: 
  print: 
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.actor }}"
      - run: echo "${{ github.run_id }}"
      - run: echo "${{ github.head_ref }}"
      - run: echo "${{ github.workspace }}"
      - run: echo "${{ github.repository }}"
      - run: echo "${{ github.repository_owner }}"
      - run: echo "${{ github.event }}"
