name: Manual
on:
  workflow_dispatch:
    inputs:
      greeting:
        type: string
        default: 'Hello, World!'
        requred: true
        descripption: 'A cheerful word'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.greeting }}"